### ISSUE TITLE
Insertion of a whitespace after closing with escape.

### ISSUE THREAD

**Issue by emanuelbuholzer** [jessepollak/slash#16]
Command inserts a whitespace after closing with escape.

_Demonstration:_

![animation](https://cloud.githubusercontent.com/assets/12075322/13444310/c7a92a2e-e005-11e5-9cad-f2c500553eb7.gif)

**Comment by jessepollak** [comment]
Thanks for the report!

**Comment by jessepollak** [comment]
This should be fixed in v0.0.12, which I'm releasing tonight — can you let me know if it's not?

Thanks!
