### ISSUE TITLE
Messenger.com /giphy problems

### ISSUE THREAD

**Issue by shxl** [jessepollak/slash#21]
Sup.

So when using the giphy command in messenger.com I've noticed a number of issues:
- [ ] the pop-up window that contains gifs after a search won't take into consideration the space around it and makes y overflow like crazy all over the place:

<img width="743" alt="screen shot 2016-03-03 at 19 25 10" src="https://cloud.githubusercontent.com/assets/9746307/13506372/bbdeb29c-e175-11e5-9742-d54af20b642c.png">

Secondly, when clicking a gif, the image doesn't insert and send, it just goes back to the menu where you can enter more slash commands, any thoughts on this?

**Comment by jessepollak** [comment]
I'm closing this in favor of a more general #24.
