### ISSUE TITLE
No emoji available in chrome

### ISSUE THREAD

**Issue by afnpires** [jessepollak/slash#34]
When using the chrome extension the following warning appears:
![image](https://cloud.githubusercontent.com/assets/5302351/14350769/323ee6d8-fcc3-11e5-9487-7886a3448014.png)

I know the emoji are a limitation in chrome, but is it not possible to import a font with the emojis and used it?

Cheers! :beers:

**Comment by ewnd9** [comment]
Chrome extensions with emoji listings may hint the realisation (I use https://chrome.google.com/webstore/detail/emoji-cheatsheet-for-gith/nojknakoailnpbjlmfkpbbhoodlolfbh?utm_source=chrome-app-launcher-info-dialog)

![image](https://cloud.githubusercontent.com/assets/1713789/14350874/91c69e26-fcfe-11e5-8ba8-2b7d975691c0.png)

**Comment by jessepollak** [comment]
Is this on Windows? Unfortunately, Chrome on Windows doesn't support native emoji and websites don't have a commonly supported format for emoji. I'm hopeful that emoji support for Windows will come soon!

if this isn't on Windows, can you reopen? Thanks!

**Comment by keysmashes** [comment]
Definitely not Windows-specific, the same ('Your browser does not support emoji') happens on Ubuntu.

**Comment by brandonsueur** [comment]
I have the same concern... #Windaube

![devon-bostick-triste-sabado-cyvx99tBf2LpS](https://media1.giphy.com/media/cyvx99tBf2LpS/giphy.gif)
