### ISSUE TITLE
Improve Wiki Acessibility

### ISSUE THREAD

**Issue by cwervo** [jessepollak/slash#37]
Small thing, [the page a user arrives at](https://github.com/jessepollak/command/wiki/Why-isn't-command-supported-on-_______-website%3F) when a page isn't supported has a GIF (the flashing "work") that flashes. It's a nice touch, but should probably be slowed down or just replaced with another fun GIF as this one can [unnecessarily trigger](https://www.webaccessibility.com/best_practices.php?best_practice_id=353) seizures, and generally just disorient or distract readers.

**Comment by jessepollak** [comment]
Thanks, removed!
