### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by jforaker** [jessepollak/slash#49]
Sometimes on page load I get this error in the console (in development):
`Uncaught TypeError: Cannot read property 'replace' of null`

This error ultimately causes the extension not to run at all.
![image](https://cloud.githubusercontent.com/assets/2042031/15083664/6ebab5e8-139c-11e6-9974-1f3e1160228b.png)

Its hard to track down exactly what causes the error because sometimes a refresh causes it to go away, other times it will load fine as expected..  Any thoughts?

**Comment by jforaker** [comment]
Looks like an issue with webpack-dev-server:

https://github.com/webpack/webpack-dev-server/issues/381

If you set the version to `1.14.0` of `webpack-dev-server` and reinstall/rebuild it works every time without error.

**Comment by jessepollak** [comment]
![lisa-vertudaches-happy-bunny-thank-you-3oEduJnper1UdNqreg](https://media4.giphy.com/media/3oEduJnper1UdNqreg/giphy.gif)
