### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by axandreo** [jessepollak/slash#50]
I am unable to create the development build. On command prompt for windows I do npm install and then do npm run dev. However, command/build doesn't exist. So I can't add the development to my chrome browser. What should I do? Are there different instructions for building on windows?

**Comment by ishu3101** [comment]
I'm also having the same issue on Windows. See issue #39.

**Comment by jessepollak** [comment]
Thanks for the report, I'm reopening #39 and closing this one.
