### ISSUE TITLE
Adding options.html to build is missing

### ISSUE THREAD

**Issue by sharmasha2nk** [jessepollak/slash#51]
options.html page is required for adding some extension settings. How to include that while building project? @jessepollak

**Comment by jessepollak** [comment]
Have you tried adding an `options.html` file to the `manifest.json` file [here](https://github.com/jessepollak/command/blob/c80f33e5324c52f7490731726eb1da983da51e0b/src/manifest.json)?

**Comment by sharmasha2nk** [comment]
Yes, but the part of adding that to build is missing. I had to manually copy that options.html to build folder to make it work. Probably need to include that html and options.js file in build.js . Any hint will also help.

**Comment by jessepollak** [comment]
I just added support for an options page and JS in [this commit](https://github.com/jessepollak/command/commit/1b63a384825f5bfc0dab35948271fce83ccd3e71). If you merge the `add-options-page` branch into yours, you should be good to go!
